### ISSUE TITLE
unexpected error error="invalid block type"

### ISSUE THREAD

**Issue by jitendra9873** [repeatedly/fluent-plugin-beats#21]
Hey,
I ran into few errors while setting up filebeat to fluentd.
errors:
```
#0 unexpected error error="invalid stored block lengths"
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:300:in `inflate'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:300:in `compressed_payload'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:171:in `feed'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:353:in `read_socket'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/lumberjack/beats/server.rb:328:in `run'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-beats-1.1.0/lib/fluent/plugin/in_beats.rb:111:in `block in run'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  2019-06-27 18:22:06 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
```

```
unexpected error error="invalid block type"

unexpected error error="invalid distance code"

unexpected error error="unsupported protocol 54"

unexpected error error="too many length or distance symbols"

unexpected error error="incorrect header check"
```

Can anyone help with this?

**Comment by waqarsky** [comment]
Was there any update on this issue?
