### ISSUE TITLE
unsupported protocol 71

### ISSUE THREAD

**Issue by lycis** [repeatedly/fluent-plugin-beats#4]
I ran into the following error when testing for our setup with fluentd and filebeat`:

```
2017-06-09 12:19:26 +0000 [error]: unexpected error error="unsupported protocol 71"
```` 

The configuration of the fluentd is actually pretty simple:

```
  <source>
    @type forward
    port 24224
  </source>
  <source>
    @type beats
    metadata_as_tag 
    port 5044
  </source>
  <match *>
    @type elasticsearch
    logstash_format true
    flush_interval 10s
    host elastic
    port 9200
  </match>
```

The complete stack trace of the error is this:
```
2017-06-09 12:19:26 +0000 [error]: unexpected error error="unsupported protocol 71"
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/lumberjack/beats/server.rb:225:in `handle_version'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/lumberjack/beats/server.rb:210:in `header'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/lumberjack/beats/server.rb:163:in `feed'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/lumberjack/beats/server.rb:342:in `read_socket'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/lumberjack/beats/server.rb:319:in `run'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-beats-0.1.2/lib/fluent/plugin/in_beats.rb:97:in `block in run'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `run_task'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (3 levels) in create_worker'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `loop'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `block (2 levels) in create_worker'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `catch'
  2017-06-09 12:19:26 +0000 [error]: /var/lib/gems/2.3.0/gems/concurrent-ruby-0.9.2/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `block in create_worker'
```

I am using the following versions:
* `fluentd`: docker image `fluent/fluentd:v0.12-debian-onbuild`
* `filebeat`:  `filebeat version 5.4.1 (amd64), libbeat 5.4.1`

Is there anything that I did wrong or can do about the error?

**Comment by repeatedly** [comment]
Hmm... beats may change their protocol.
I check it with latest beats.

**Comment by repeatedly** [comment]
I tested with filebeat 5.4.1 /  latest fluent-plugin-beats and there is no problem.
I assume other program sends data to fluent-plugin-beats.
lumberjack protocols now are only 1 or 2, so 71 seems garbage.

**Comment by lycis** [comment]
I will check up on this within the next days and see if I can again reproduce it. Maybe I'll be able to provide a test setup that shows the error.

**Comment by cirocosta** [comment]
Hey @lycis , is this still a thing? Still facing such problem?

**Comment by lycis** [comment]
The issue is not reccuring since we updated some of the involved components
